### PR TITLE
bsc panfil

### PR DESCRIPTION
**Pull request by alexandrinapanfil**

### CODE REVIEW

**Review by ackxolotl — APPROVED** [review]

**Comment by ackxolotl** [comment]
Looks good to me!

**Comment by ackxolotl** [comment]
Is there also a presentation?

**Comment by bhatotia** [comment]
I think the presentation is missing. @alexandrinapanfil ?

**Comment by alexandrinapanfil** [comment]
I added the presentation in archive/2021/winter/talks/bsc_panfil_memory_safety_for_persistent_memory_safe_persistent_pointers.pdf . It just has the same name as the thesis

**Comment by ackxolotl** [comment]
Awesome, thanks! I missed that.

**Pull request merged**
